update

diff --git a/movie-cli-es b/movie-cli-es
--- a/movie-cli-es
+++ b/movie-cli-es
@@ -1,14 +1,17 @@
 #!/bin/bash
 
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
+# set -euo pipefail
+
 # Script para buscar y reproducir películas, series y anime de Cuevana3
 
-# Dependencias requeridas: mpv, yt-dlp, fzf, curl
+# Dependencias requeridas: mpv, yt-dlp, fzf, curl, ffmpeg
 
 others_base_url="https://cuevana3.ch"
 anime_base_url="https://monoschinos2.com"
 doramas_base_url="https://www.doramasyt.com"
 spn_search_endpoint="/buscar?q="
-movies_search_endpoint="/search.html?keyword="
+eng_search_endpoint="/search.html?keyword="
 dir="$HOME/.cache/movies"
 state_file="$dir/state"
 bookmarks="$dir/bookmarks"
@@ -17,26 +20,25 @@ dir_downloads="$HOME/Downloads/movies"
 
 [ ! -d "$dir" ] && mkdir "$dir"
 
-# checks if dependencies are present
-dep_ch() {
+# comprueba si las dependencias están presentes
+dep_ch(){
     for dep; do
         command -v "$dep" >/dev/null || die "Program \"$dep\" not found. Please install it."
     done
 }
+dep_ch "curl" "sed" "grep" "mpv" "fzf" "yt-dlp" "ffmpeg" || true
 
 die() {
     printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
     exit 1
 }
 
-dep_ch "curl" "sed" "grep" "mpv" "fzf" "yt-dlp" "ffmpeg" || true
-
-
 downloads() {
     local title_m3u8
     local m3u8_part1
     local m3u8_part2
     local mp4
+    local links
     [ ! -d "$dir_downloads" ] && mkdir "$dir_downloads"
     [ -n "$1" ] || die "No hay enlace"
     title_m3u8=$(echo "$titleG" | cut -d '/' -f 5 | tr '-' ' ')
@@ -90,7 +92,7 @@ search_globar(){
     results_anime=$(curl -s "$anime_url" | grep "$1" | grep href | cut -d\" -f 2 | tr '-' ' ' | sed 's#^https://monoschinos2.com/##')
     local dorama_url="${doramas_base_url}${spn_search_endpoint}$1"
     results_dorama=$( curl -s "$dorama_url" | grep "dorama/" | cut -d\" -f 2 | sed 's#^https://www.doramasyt.com/##' |  tr '-' ' ' )
-    local others_url="${others_base_url}${movies_search_endpoint}$1"
+    local others_url="${others_base_url}${eng_search_endpoint}$1"
     results_others=$(curl -s "$others_url" | grep "$1" | grep href | cut -d\" -f 2 | tr '-' ' ' )
 
     if [ -n "$results_anime" ]; then
@@ -108,77 +110,89 @@ search_globar(){
 }
 
 get_video_links() {
-    local video_links
-    local links_base64
+    local video_links=()
+    local links_decoders=()
     local excluded_sites=("filemoon" "dood" "azipcd")
+
     case "$1" in
-        *ver*|*anime*) mapfile -t links_base64 < <(curl -s "$1" | grep -o 'data-player="[^"]*"' | awk -F'"' '{print $2}' | sort | uniq)
-            for link in "${links_base64[@]}"; do
-                decoded_link=$(printf "%s" "$link" | base64 -d | cut -d '=' -f 2)
+        *ver*|*anime*)
+            mapfile -t links_decoders < <(curl -s "$1" | grep -o 'data-player="[^"]*"' | awk -F'"' '{print $2}' | sort -u)
+
+            for link in "${links_decoders[@]}"; do
+                decoded_link=$(printf "%s\n" "$link" | base64 -d | cut -d '=' -f 2)
                 excluded=false
+
                 for site in "${excluded_sites[@]}"; do
                     if [[ $decoded_link == *"$site"* ]]; then
                         excluded=true
                         break
                     fi
                 done
+
                 if [ "$excluded" = false ]; then
-                    links_decoders+=("$decoded_link")
+                    video_links+=("$decoded_link")
                 fi
             done
-            video_links=("${links_decoders[@]}")  # Store all decoded links in video_links
             ;;
-        *) mapfile -t video_links < <(curl -s "$1" | grep data-video | awk '!/dood|azipcdn|pelisplay/' | cut -d\" -f2 | grep https) ;;
+        *)
+            mapfile -t video_links < <(curl -s "$1" | grep data-video | awk '!/dood|azipcdn|pelisplay/' | cut -d\" -f2 | grep https)
+            ;;
     esac
-    echo "${video_links[@]}"
+
+    printf "%s\n" "${video_links[@]}"
+}
+
+replay(){
+    local link
+    local title
+    title=$(echo "$titleG" | cut -d '/' -f 5 | tr '-' ' ')
+    for link in "${@}"; do
+        if mpv --title="$title" "$link";
+        then
+            history save "$result_url"
+            echo "$result_url"
+        fi
+    done
 }
 
 next(){
     local video_links
     local title
+    local links
     title=$(echo "$1" | cut -d '/' -f5 | tr -d '0-9' )
     next_episode=$(curl -s "$1" | grep "$title" | cut -d\" -f 2 | uniq -d )
     result_url=$next_episode
     titleG="$next_episode"
-    links=$(get_video_links "$next_episode")
-    [ -n "$links" ] || die "no hay enlaces disponible"
+    mapfile -t links < <(get_video_links "$next_episode")
+    [ -n "${links[*]}" ] || die "no hay enlaces disponible"
     replay "${links[@]}"
 }
 
+
 play(){
+    local result_url
     local options=("Reproducir" "Siguiente" "Agregar a favoritos" "Descargar" "Volver al menú" "Salir")
     local choice
     while true ; do
         choice=$(printf '%s\n' "${options[@]}" | fzf )
         case "$choice" in
-            'Reproducir') replay "$1" ;;
+            'Reproducir') replay "${@}" ;;
             'Siguiente') next "$result_url" ;;
-            'Descargar') downloads "$1" ;;
-            'Salir' ) break  ;;
+            'agrega a favoritos') bookmarks save "$result_url" ;;
+            'Descargar') downloads "${@}" ;;
+            'Salir' ) break 4 ;;
         esac
     done
 }
 
-replay(){
-    title=$(echo "$titleG" | cut -d '/' -f 5 | tr '-' ' ')
-    for link in "${@}"; do
-        if mpv --title="$title" "$link";
-        then
-            echo "bien"
-            # history "$result_url"
-        else
-            break 2
-        fi
-    done
-}
-
 last_viewed(){
+    local result_url
     local links
     if [ -f "$state_file" ];
     then
         result_url=$(cat "$state_file")
-        links=$(get_video_links "$result_url")
-        [ -n "$links" ] || die "no hay enlaces disponible"
+        titleG=$(echo "$result_url" | cut -d '/' -f 5 | tr '-' ' ')
+        mapfile -t links < <(get_video_links "$result_url")
         replay "${links[@]}"
     else
         die "no hay ultima vez"
@@ -186,7 +200,9 @@ last_viewed(){
 }
 
 bookmarks(){
+    local result_url
     local select_bookmarks
+    local links
     case "$1" in
         'save') if ! pgrep -Fxq "$2" "$bookmarks";
             then
@@ -196,8 +212,8 @@ bookmarks(){
             then
                 select_bookmarks=$(fzf < "$bookmarks" )
                 result_url=$select_bookmarks
-                links=$(get_video_links "$result_url")
-                [ -n "$links" ] || die "no hay enlaces disponible"
+                mapfile -t links < <(get_video_links "$result_url")
+                [ -n "${links[*]}" ] || die "no hay enlaces disponible"
                 replay "${links[@]}"
             else
                 die "No hay favoritos"
@@ -207,6 +223,7 @@ bookmarks(){
 
 history(){
     local select_history
+    local result_url
     case "$1" in
         'save') if ! grep -Fxq "$2" "$history";
             then
@@ -216,19 +233,17 @@ history(){
             then
                 select_history=$( fzf < "$history" )
                 result_url=$select_history
-                links=$(get_video_links "$result_url")
-                [ -n "$links" ] || die "no hay enlaces disponible"
+                mapfile -t links < <(get_video_links "$result_url")
+                [ -n "${links[*]}" ] || die "no hay enlaces disponible"
                 replay "${links[@]}"
-
             fi ;;
     esac
 }
 
 main(){
-    local query
-    local lists
     local choice
     local title
+    local links
     printf "\33[2K\r\033[1;36mBuscar: \033[0m" && read -r query
     query=$(printf "%s" "$query" | sed "s| |+|g")
     lists=$(search_globar "$query")
@@ -238,9 +253,9 @@ main(){
     title=$(echo "$get_url" | cut -d '/' -f5 | tr '-' ' ')
     result_url=$(get_episode "$get_url")
     [ -n "$result_url" ] || die "No hay episodios"
-    links=$(get_video_links "$result_url")
-    [ -n "$links" ] || die "No hay enlaces disponibles"
-    export titleG="$result_url"
+    mapfile -t links < <(get_video_links "$result_url")
+    [ -n "${links[*]}" ] || die "No hay enlaces disponibles"
+    titleG="$result_url"
     play "${links[@]}"
 }
 
